import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';
import { AppContextProvider } from '@/providers/app-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import ToasterProvider from '@/providers/toast-provider';
import '@/styles/globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'E-commerce',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png'
  }
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body className={cn('min-h-screen bg-[#f4f6f8]', inter.className)}>
          <AppContextProvider>
            <ThemeProvider attribute='class' defaultTheme='light' enableSystem disableTransitionOnChange>
              {children}
            </ThemeProvider>
          </AppContextProvider>
          <ToasterProvider></ToasterProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
